# Generated by Django 4.0 on 2022-01-21 18:26

import api_test.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date_found', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=api_test.models.brand_rename)),
            ],
        ),
        migrations.AddField(
            model_name='accessory',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_test.brand'),
        ),
    ]
