# Generated by Django 4.0 on 2022-01-22 18:08

import api_test.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0003_alter_accessory_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=api_test.models.meal_rename)),
            ],
        ),
    ]
