# Generated by Django 4.0 on 2022-01-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0004_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
