# Generated by Django 4.0 on 2022-01-23 21:38

import api_test.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0005_remove_accessory_brand_delete_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='API_Brand',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date_found', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=api_test.models.brand_rename)),
            ],
        ),
    ]
