# Generated by Django 4.0 on 2022-01-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0006_api_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessory',
        ),
    ]
