# Generated by Django 4.0 on 2022-01-18 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miren_collection', '0004_outfit'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='top',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='miren_collection.top'),
            preserve_default=False,
        ),
    ]
