# Generated by Django 4.0 on 2022-01-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miren_collection', '0005_outfit_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='image',
            field=models.ImageField(upload_to='tops/'),
        ),
    ]
