# Generated by Django 4.0 on 2022-01-19 20:24

from django.db import migrations, models
import miren_collection.models


class Migration(migrations.Migration):

    dependencies = [
        ('miren_collection', '0008_bottom_hat_outerwear_shoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottom',
            name='image',
            field=models.ImageField(upload_to=miren_collection.models.bot_rename),
        ),
        migrations.AlterField(
            model_name='hat',
            name='image',
            field=models.ImageField(upload_to=miren_collection.models.hat_rename),
        ),
        migrations.AlterField(
            model_name='outerwear',
            name='image',
            field=models.ImageField(upload_to=miren_collection.models.outerwear_rename),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='image',
            field=models.ImageField(upload_to=miren_collection.models.shoes_rename),
        ),
    ]
