# Generated by Django 4.0 on 2022-01-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miren_collection', '0009_alter_bottom_image_alter_hat_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shoes',
            new_name='Shoe',
        ),
    ]
