# Generated by Django 4.0 on 2022-01-19 21:12

from django.db import migrations, models
import django.db.models.deletion
import miren_collection.models


class Migration(migrations.Migration):

    dependencies = [
        ('miren_collection', '0010_rename_shoes_shoe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date_found', models.DateField()),
                ('logo', models.ImageField(upload_to=miren_collection.models.brand_rename)),
            ],
        ),
        migrations.CreateModel(
            name='Handbag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to=miren_collection.models.shoes_rename)),
            ],
        ),
        migrations.CreateModel(
            name='Sunglass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to=miren_collection.models.shoes_rename)),
            ],
        ),
        migrations.AddField(
            model_name='top',
            name='brand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='miren_collection.brand'),
            preserve_default=False,
        ),
    ]
