# Generated by Django 4.0 on 2022-01-20 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miren_collection', '0011_brand_handbag_sunglass_top_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottom',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miren_collection.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hat',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miren_collection.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outerwear',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miren_collection.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoe',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miren_collection.brand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='handbag',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miren_collection.brand'),
        ),
        migrations.AlterField(
            model_name='sunglass',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miren_collection.brand'),
        ),
    ]
