# Generated by Django 4.0 on 2022-01-20 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miren_collection', '0012_bottom_brand_hat_brand_outerwear_brand_shoe_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='top',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miren_collection.top'),
        ),
    ]
