# Generated by Django 4.0 on 2022-01-20 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miren_collection', '0013_outfit_description_alter_outfit_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='bottom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miren_collection.bottom'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='concept',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='handbag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miren_collection.handbag'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='hat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miren_collection.hat'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='outerwear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miren_collection.outerwear'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='shoes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miren_collection.shoe'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='sunglass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miren_collection.sunglass'),
        ),
    ]
