# Generated by Django 4.0 on 2022-01-20 03:03

from django.db import migrations, models
import miren_collection.models


class Migration(migrations.Migration):

    dependencies = [
        ('miren_collection', '0014_outfit_bottom_outfit_concept_outfit_handbag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottom',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bottom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=miren_collection.models.bot_rename),
        ),
        migrations.AlterField(
            model_name='brand',
            name='date_found',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=miren_collection.models.brand_rename),
        ),
        migrations.AlterField(
            model_name='handbag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=miren_collection.models.shoes_rename),
        ),
        migrations.AlterField(
            model_name='hat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=miren_collection.models.hat_rename),
        ),
        migrations.AlterField(
            model_name='outerwear',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='outerwear',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=miren_collection.models.outerwear_rename),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=miren_collection.models.shoes_rename),
        ),
        migrations.AlterField(
            model_name='sunglass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=miren_collection.models.shoes_rename),
        ),
        migrations.AlterField(
            model_name='top',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='top',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=miren_collection.models.top_rename),
        ),
    ]
