# Generated by Django 4.0 on 2022-01-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miren_collection', '0015_alter_bottom_description_alter_bottom_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
