# Generated by Django 4.0 on 2022-01-25 17:31

from django.db import migrations, models
import django.db.models.deletion
import miren_collection.models


class Migration(migrations.Migration):

    dependencies = [
        ('miren_collection', '0017_alter_top_description_alter_top_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=miren_collection.models.accessory_rename)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miren_collection.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('belong_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='hat',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='sunglass',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='handbag',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='hat',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='shoes',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='sunglass',
        ),
        migrations.DeleteModel(
            name='Handbag',
        ),
        migrations.DeleteModel(
            name='Hat',
        ),
        migrations.DeleteModel(
            name='Sunglass',
        ),
        migrations.AddField(
            model_name='accessory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miren_collection.category'),
        ),
    ]
