# Generated by Django 4.0 on 2022-01-25 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miren_collection', '0018_accessory_category_remove_hat_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='logo',
            new_name='image',
        ),
    ]
