# Generated by Django 4.0 on 2022-01-26 20:11

from django.db import migrations, models
import django.db.models.deletion
import miren_collection.models


class Migration(migrations.Migration):

    dependencies = [
        ('miren_collection', '0019_rename_logo_brand_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='bottom',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='outerwear',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='top',
        ),
        migrations.AddField(
            model_name='outfit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=miren_collection.models.shoes_rename),
        ),
        migrations.CreateModel(
            name='OutfitAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miren_collection.accessory')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miren_collection.outfit')),
            ],
        ),
    ]
