# Generated by Django 4.0 on 2022-01-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miren_collection', '0021_alter_outfitaccessory_accessory_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='outfitaccessory',
            unique_together={('outfit',)},
        ),
    ]
