# Generated by Django 4.0 on 2022-01-26 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miren_collection', '0024_alter_outfitaccessory_accessory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='bottom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miren_collection.bottom'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='outerwear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miren_collection.outerwear'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='shoe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miren_collection.shoe'),
        ),
        migrations.CreateModel(
            name='OutfitTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tops', to='miren_collection.outfit')),
                ('top', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to='miren_collection.top')),
            ],
            options={
                'unique_together': {('outfit', 'top')},
            },
        ),
    ]
