# Generated by Django 4.0 on 2022-01-29 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miren_collection', '0026_alter_outfittop_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottom',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miren_collection.category'),
        ),
        migrations.AlterField(
            model_name='outerwear',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miren_collection.category'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='accessory',
            field=models.ManyToManyField(blank=True, related_name='outfits', to='miren_collection.Accessory'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='top',
            field=models.ManyToManyField(blank=True, related_name='outfits', to='miren_collection.Top'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miren_collection.category'),
        ),
        migrations.AlterField(
            model_name='top',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miren_collection.category'),
        ),
    ]
