# Generated by Django 4.0 on 2022-01-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miren_collection', '0027_alter_bottom_category_alter_outerwear_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottom',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='outerwear',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='top',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
