# Generated by Django 4.0 on 2022-01-29 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miren_collection', '0028_alter_bottom_category_alter_outerwear_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottom',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miren_collection.category'),
        ),
        migrations.AlterField(
            model_name='outerwear',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miren_collection.category'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miren_collection.category'),
        ),
        migrations.AlterField(
            model_name='top',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miren_collection.category'),
        ),
    ]
