# Generated by Django 4.0 on 2022-01-29 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miren_collection', '0029_alter_bottom_category_alter_outerwear_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfit',
            old_name='accessory',
            new_name='accessories',
        ),
        migrations.RenameField(
            model_name='outfit',
            old_name='top',
            new_name='tops',
        ),
    ]
