# Generated by Django 4.0 on 2022-01-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miren_collection', '0030_rename_accessory_outfit_accessories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='accessories',
            field=models.ManyToManyField(blank=True, null=True, related_name='outfits', to='miren_collection.Accessory'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='tops',
            field=models.ManyToManyField(blank=True, null=True, related_name='outfits', to='miren_collection.Top'),
        ),
    ]
