# Generated by Django 4.0 on 2022-01-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miren_collection', '0031_alter_outfit_accessories_alter_outfit_tops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='accessories',
            field=models.ManyToManyField(blank=True, related_name='outfits', to='miren_collection.Accessory'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='tops',
            field=models.ManyToManyField(blank=True, related_name='outfits', to='miren_collection.Top'),
        ),
    ]
